language: python
python:
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
  - pip install tensorflow
  - pip install pygraphviz
  - pip install tqdm

script: python -m unittest

