site_name: TensorX Documentation
site_favicon: assets/images/icon.png


# Repository
repo_name: davidenunes/tensorx
repo_url: https://github.com/davidenunes/tensorx
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016 - 2020 Davide Nunes

docs_dir: "docs/sources"

markdown_extensions:
  - admonition
  - codehilite:
      use_pygments: true
      noclasses: true
      pygments_style: tango
  - pymdownx.arithmatex


plugins:
  - search

extra_css:
  - 'assets/css/extra.css'

# for mathjax
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: 'white'
  logo: 'assets/images/logo_full.svg'
  favicon: 'assets/images/tx.png'
  features:
    - navigation.tabs
    - instant
nav:
  - Home: index.md
  - Getting Started:
      - Installation: start/install.md
      - Tutorial: start/tutorial.md
  - API:
    - Layers:
        - Overview: api/index.md
        - Linear: api/layers/Linear.md
        - Activation: api/layers/Activation.md
        - MHAttention: api/layers/MHAttention.md
    - Ops: api/ops.md
    - Train:
        - Model: train/model.md
  - Contributing: contributing.md


