site_name: TensorX Documentation


# Repository
repo_name: davidenunes/tensorx
repo_url: https://github.com/davidenunes/tensorx
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016 - 2020 Davide Nunes

docs_dir: "docs/sources"

markdown_extensions:
  - admonition
  - codehilite:
      use_pygments: true
      noclasses: true
      pygments_style: tango
  - pymdownx.arithmatex


plugins:
  - search

extra_css:
  - 'assets/css/extra.css'

# for mathjax
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: 'white'
  logo: 'assets/images/logo_full.svg'
  favicon: 'assets/images/tx.png'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - instant
nav:
  - Home: index.md
  - Getting Started:
      - Installation: start/install.md
      - Tutorial: start/tutorial.md
  - API:
    - layers:
        - Overview: api/layers/index.md
        - Lambda: api/layers/Lambda.md
        - Input: api/layers/Input.md
        - Linear: api/layers/Linear.md
        - Lookup: api/layers/Lookup.md
        - Activation: api/layers/Activation.md
    - ops: api/ops.md
    - math: api/math.md
    - init: api/init.md
    - activation: api/activation.md
    - loss: api/loss.md
    - metrics: api/metrics.md

  - Contributing: contributing.md


